### ISSUE TITLE
Request Failed

### ISSUE THREAD

**Issue by engrjawadulhassan** [SergejBre/SynchroTime#1]
Hello,

I am using synchro_RTC.ino for DS3231 module. Connected Pins According to picture given on git.
Vcc = 5v
GND = GND
SDA = A4
SCL = A5
SQW = D2

But after short time , and sometime after click only , GUI said "status request failed", its not working constantly for 2 mins.
Have a look into this. I am unable to check my module properly. 

![Capture](https://user-images.githubusercontent.com/54907607/130032855-d69991cc-2057-4e75-b4d5-6f88117d6123.JPG)

**Comment by Croft5** [comment]
Hi,

I have frequently experianced the same issue but all I do is to connect again, and again and again and it will suddendly work.
A bit of a pain but managble once you know about this.

Overall this is an excellent program and has allowed me to adjust my DS3231 so it runns very accuratly.
Also worth mentioning that you can input adjustment values in 0.1 steps.
Orginally I thought it had to be in steps of +/- 1.

**Comment by SergejBre** [comment]
Hi, there may be several reasons. First, check the serial port settings on your system. If that doesn't work, then try to find a more reliable USB cable. The influence of electromagnetic interference from a telephone operating near is possible. If you are working with a Chinese clone of Arduino Nano with a port emulator on a CH340G chip, then it makes sense to lower the operating Baud Rate to 57600 baud. If this does not help, then disable "Status Control" in the settings as shown in the figure below.
![settings](https://user-images.githubusercontent.com/35642212/131100535-e8b4fca2-75da-4c8a-aab2-8ba3f99a8f87.png)

**Comment by SergejBre** [comment]
I assume that your problem is solved.

**Comment by BluDvD** [comment]
Hi
I am trying to use your program but when i compile it, outputs a error. But if i change the time_t to time_v, it compiles normally. ![2](https://user-images.githubusercontent.com/63650234/151591269-44b8bea1-d6ad-4677-8003-89ff34b3684d.PNG)

When it compiles normally, i cant sync the RTC module to the program.
![3](https://user-images.githubusercontent.com/63650234/151591307-caecce09-9875-4cf5-b9f3-51044967ea18.PNG)

The connections are: 

Vcc = 3.3v(because if i use 5v, the power led dont come on...)
GND = GND
SDA = A4
SCL = A5
SQW = D2
